### ISSUE TITLE
[ci.yml] Automatic generation of the hardware code not integrated

### ISSUE THREAD

**Issue by luizvilla** [owntech-foundation/Documentation#4]
**Description**

While debugging the Documentation we have come across the fact that `ci.yml` does not have the line necessary to generate the hardware. Such as: 

```
      - name: Checkout OwnTech Twist V1_4 repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/twist
          ref: TWIST-V1.4.X
          path: docs/twistV14
          sparse-checkout: |
            docs/getting_started.md
            docs/images/
            docs/images/*
          sparse-checkout-cone-mode: false
```

They should be added to the automatic `ci.yml`
